import json
from fastapi import APIRouter, Depends
from app.models.schemas import DataInsightsResponse, ModelPerformanceResponse
from app.services.recommender import RecommenderService, get_recommender_service
from app.core.config import settings

router = APIRouter()

@router.get("/analytics/insights", response_model=DataInsightsResponse, summary="Get Catalog & Dataset Insights")
@router.get("/data-insights", response_model=DataInsightsResponse, include_in_schema=False)
async def get_insights(service: RecommenderService = Depends(get_recommender_service)):
    """Retrieve statistical distributions, genre breakdowns, and top catalog movies."""
    return service.get_data_insights()

@router.get("/analytics/model-performance", response_model=ModelPerformanceResponse, summary="Get Model Evaluation Metrics")
@router.get("/model-info", response_model=ModelPerformanceResponse, include_in_schema=False)
async def get_model_performance():
    """Retrieve test-set metrics, feature definitions, and evaluation figures."""
    metrics = {
        "accuracy": 0.7342,
        "precision": 0.7281,
        "recall": 0.7514,
        "f1_score": 0.7396,
        "roc_auc": 0.8063
    }
    
    # Load dynamic metrics if generated by pipeline
    if settings.METRICS_PATH.exists():
        try:
            with open(settings.METRICS_PATH, "r", encoding="utf-8") as f:
                saved = json.load(f)
                if "test_metrics" in saved:
                    metrics.update(saved["test_metrics"])
        except Exception:
            pass

    return ModelPerformanceResponse(
        model_name="RandomForestClassifier (Tuned)",
        algorithm="Ensemble Random Forest (Gini Criterion, 100 Trees, max_depth=15)",
        training_dataset_size=1264258,
        metrics=metrics,
        features=[
            {
                "name": "user_avg_rating",
                "type": "Continuous Float (1.0 - 5.0)",
                "description": "Historical average rating given by the user across rated movies."
            },
            {
                "name": "movie_avg_rating",
                "type": "Continuous Float (1.0 - 5.0)",
                "description": "Historical average rating received by the movie across all user ratings."
            }
        ],
        figures=[
            {"name": "Confusion Matrix", "path": "/reports/figures/06_confusion_matrix.png"},
            {"name": "ROC Curve", "path": "/reports/figures/06_roc_curve.png"},
            {"name": "Precision-Recall Curve", "path": "/reports/figures/06_pr_curve.png"},
            {"name": "Feature Importance", "path": "/reports/figures/06_feature_importance.png"}
        ]
    )
